NumPy Retail Analytics Assignment

Business Scenario

You are working as a Data Analyst for SmartMart Retail Stores. The company operates five stores in different cities and sells six major product categories.

Management wants to analyze sales performance, expenses, profits, targets, discounts, inventory, and store-level performance using NumPy.

You are provided with two main NumPy arrays:

sales_data — monthly sales revenue generated by each store for different product categories. cost_data — total cost incurred by each store for the same product categories.

Part 1: Dataset Creation

In [1]:
import numpy as np

# Store names
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])

# Product categories
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])

# Sales revenue in rupees
# Rows represent stores
# Columns represent product categories

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])

# Cost incurred in rupees
# Rows represent stores
# Columns represent product categories

cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])


print("Stores:")
print(stores)

print("\nProduct Categories:")
print(categories)

print("\nSales Data:")
print(sales_data)

print("\nCost Data:")
print(cost_data)

Stores:
['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune']

Product Categories:
['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Beauty' 'Sports']

Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Cost Data:
[[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Part 2: Basic Array Understanding

Question 1: Array Dimensions The finance manager wants to confirm how many stores and product categories are present in the data.

Write NumPy code to display:

Number of dimensions in sales_data Shape of sales_data Total number of values Data type of the array Memory occupied by the array

In [2]:
import numpy as np
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
print("\nSales Data:")
print(sales_data)
shape = sales_data.shape
print("\nShape of sales_data:", shape)
total_values = sales_data.size
print("\nTotal number of values:", total_values)
data_type = sales_data.dtype
print("\nData type of the array:", data_type)
memory_occupied = sales_data.nbytes
print("\nMemory occupied by the array:", memory_occupied, "bytes")


Sales Data:
[[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]

Shape of sales_data: (5, 6)

Total number of values: 30

Data type of the array: int64

Memory occupied by the array: 240 bytes


Question 2: Store and Category Count Calculate the following:

Total number of stores Total number of product categories Total number of store-category combinations

In [3]:
import numpy as np
total_number_of_stores = len(stores)
print("Total number of stores:", total_number_of_stores)
total_number_of_product_categories = len(categories)
print("Total number of product categories:", total_number_of_product_categories)
total_number_of_store_category_combinations = total_number_of_stores * total_number_of_product_categories
print("Total number of store-category combinations:", total_number_of_store_category_combinations)

Total number of stores: 5
Total number of product categories: 6
Total number of store-category combinations: 30


Question 3: Sales Data Type Conversion The reporting application requires sales values in floating-point format.

Convert sales_data into:

float32 float64 Compare the memory used by both arrays.

In [4]:
import numpy as np
convert_sales_data_to_float32 = sales_data.astype(np.float32)
print("\nSales Data (float32):")
print(convert_sales_data_to_float32)
convert_sales_data_to_float64 = sales_data.astype(np.float64)
print("\nSales Data (float64):")
print(convert_sales_data_to_float64)


Sales Data (float32):
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]

Sales Data (float64):
[[ 850000.  420000.  310000.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.  310000.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.  510000.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.  175000.  205000.]]


Part 3: Indexing and Data Extraction
Question 4: Bengaluru Store Analysis

The Bengaluru regional manager wants to review sales for all product categories.

Extract and display the complete sales row for Bengaluru.

In [5]:
import numpy as np
Bengulur_sales = sales_data[0, :]
print("Sales for Bengaluru:")
print(Bengulur_sales)

Sales for Bengaluru:
[850000 420000 310000 275000 190000 225000]


Question 5: Mumbai Cost Analysis

Extract the total cost incurred by the Mumbai store for all product categories.

In [6]:
import numpy as np
Mumbai_total_cost = cost_data[3, :]
print("Total cost incurred by Mumbai:")
print(Mumbai_total_cost)

Total cost incurred by Mumbai:
[790000 390000 265000 250000 165000 205000]


Question 6: Electronics Sales Across Stores

The electronics department wants to compare its sales performance across all five stores.

Extract the Electronics sales column from sales_data.

In [7]:
import numpy as np
Electronics_sales = sales_data[:, 0]
print("Electronics sales across stores:")
print(Electronics_sales)

Electronics sales across stores:
[ 850000  780000  920000 1050000  690000]


Question 7: Clothing Cost Across Stores

Extract the Clothing cost for every store from cost_data.

In [8]:
import numpy as np
clothing_cost = cost_data[2, :]
print("Clothing cost across stores:")
print(clothing_cost)

Clothing cost across stores:
[700000 295000 245000 195000 120000 155000]


Question 8: Hyderabad Furniture Performance

Find the following for Hyderabad:

Furniture sales Furniture cost Furniture profit

In [9]:
import numpy as np
Hyderabad_furniture_sale = sales_data[1, 3]
print("Furniture sales in Hyderabad:", Hyderabad_furniture_sale)
Hyderabad_furniture_cost = cost_data[1, 3]
print("Furniture cost in Hyderabad:", Hyderabad_furniture_cost)
profit_data = sales_data - cost_data
Hyderabad_furniture_sale = profit_data[1, 3]
print("Furniture profit in Hyderabad:", Hyderabad_furniture_sale)

Furniture sales in Hyderabad: 310000
Furniture cost in Hyderabad: 225000
Furniture profit in Hyderabad: 85000


Question 9: Chennai Category Range

Extract Chennai’s sales for the following categories:

Groceries Clothing Furniture Use array slicing.

In [10]:
import numpy as np
Chennai_sales = sales_data[2, 1:4]
print("Sales for Chennai:")
print(Chennai_sales)
Groceries_sales = sales_data[2, 1]
print("Groceries sales in Chennai:", Groceries_sales)
Clothing_sales = sales_data[2, 2]
print("Clothing sales in Chennai:", Clothing_sales)
Furniture_sales = sales_data[2, 3]
print("Furniture sales in Chennai:", Furniture_sales)

Sales for Chennai:
[390000 340000 260000]
Groceries sales in Chennai: 390000
Clothing sales in Chennai: 340000
Furniture sales in Chennai: 260000


Question 10: Selected Store Analysis

Extract sales data for:

Bengaluru Chennai Pune Include only:

Electronics Clothing Beauty Use advanced indexing.

In [11]:
import numpy as np
Benguluru_sales = sales_data[0, [0, 2, 4]]
print("Sales for Bengaluru:", Benguluru_sales)
Chennai_sales = sales_data[2, [2, 3,4]]
print("Sales for Chennai:", Chennai_sales)
Pune_sales = sales_data[4, [0, 2, 5]]
print("Sales for Pune:", Pune_sales)

Sales for Bengaluru: [850000 310000 190000]
Sales for Chennai: [340000 260000 185000]
Sales for Pune: [690000 280000 205000]


Part 4: Sales Aggregation

Question 11: Company-Wide Sales
Calculate the total sales revenue generated by all stores and all categories.

In [12]:
import numpy as np
Total_sales = np.sum(sales_data)
print("Total sales revenue generated by all stores and all categories:", Total_sales)

Total sales revenue generated by all stores and all categories: 11675000


Question 12: Store-Wise Sales Calculate total sales revenue for each store.

Display the result together with the store names.

Expected output format: Bengaluru: total sales
Hyderabad: total sales
Chennai: total sales
Mumbai: total sales
Pune: total sales

In [13]:
import numpy as np
total_sales_by_store = np.sum(sales_data, axis=1)
for i in range(len(stores)):
    print(stores[i] + ": " + str(total_sales_by_store[i]))

Bengaluru: 2270000
Hyderabad: 2295000
Chennai: 2310000
Mumbai: 2820000
Pune: 1980000


Question 13: Category-Wise Sales

Calculate total sales for each product category across all stores.

Display each category name with its total sales.

In [14]:
import numpy as np
total_sales_by_category = np.sum(sales_data, axis=0)
for i in range(len(categories)):
    print(categories[i] + ": " + str(total_sales_by_category[i]))

Electronics: 4290000
Groceries: 2185000
Clothing: 1600000
Furniture: 1415000
Beauty: 1010000
Sports: 1175000


Question 14: Average Sales Per Store Calculate the average sales generated by each store across all six product categories.

In [15]:
import numpy as np
average_sales_per_store = np.mean(sales_data, axis=1)
for i in range(len(stores)):
    print(stores[i]+ ": "+ str(average_sales_per_store))

Bengaluru: [378333.33333333 382500.         385000.         470000.
 330000.        ]
Hyderabad: [378333.33333333 382500.         385000.         470000.
 330000.        ]
Chennai: [378333.33333333 382500.         385000.         470000.
 330000.        ]
Mumbai: [378333.33333333 382500.         385000.         470000.
 330000.        ]
Pune: [378333.33333333 382500.         385000.         470000.
 330000.        ]


Question 15: Average Sales Per Category

Calculate the average sales of each product category across the five stores.

In [16]:
import numpy as np
average_sales_per_category = np.mean(sales_data, axis=0)
for i in range(len(categories)):
    print(categories[i] + ": " + str(average_sales_per_category[i]))

Electronics: 858000.0
Groceries: 437000.0
Clothing: 320000.0
Furniture: 283000.0
Beauty: 202000.0
Sports: 235000.0


Question 16: Highest-Selling Store

Identify:

Index of the store with the highest total sales Name of the store Total sales generated by that store Use np.argmax().

In [17]:
import numpy as np
index_of_highest_selling_store = np.argmax(total_sales_by_store)
print("Index of the store with the hight total sales: ",index_of_highest_selling_store)
name_of_highest_selling_store = stores[index_of_highest_selling_store]
print("Name of the store with the highest total sales: ",name_of_highest_selling_store)
total_sales_of_highest_selling_store = total_sales_by_store[index_of_highest_selling_store]
print("Total sales generated by the store with the highest total sales: ",total_sales_of_highest_selling_store)

Index of the store with the hight total sales:  3
Name of the store with the highest total sales:  Mumbai
Total sales generated by the store with the highest total sales:  2820000


Question 17: Lowest-Selling Store

Identify the store with the lowest overall sales.

Use np.argmin().

In [18]:
import numpy as np
lowest_selling_storre = np.argmin(total_sales_by_store)
print("Index of the store with the lowest overall sales: ",lowest_selling_storre)

Index of the store with the lowest overall sales:  4


Question 18: Highest-Selling Category

Find the product category that generated the highest total sales across the company.

In [19]:
import numpy as np
highest_selling_category = np.argmax(total_sales_by_category)
print("Product category that generated the hight total sales across the company: ", highest_selling_category)

Product category that generated the hight total sales across the company:  0


Question 19: Lowest-Selling Category

Find the product category with the lowest total sales across all stores.

In [20]:
import numpy as np
lowest_selling_category = np.argmin(total_sales_by_category)
print("Product category with the lowest total sales across all stores: ", lowest_selling_category)

Product category with the lowest total sales across all stores:  4


Part 5: Cost Analysist

Question 20: Total Company Cost

Calculate the total cost incurred by SmartMart across all stores and product categories.

In [21]:
import numpy as np
total_cost = np.sum(cost_data)
print("Total cost incurred by SmartMart across all stores and product categories: ", total_cost)

Total cost incurred by SmartMart across all stores and product categories:  8600000


Question 21: Store-Wise Cost

Calculate the total cost incurred by each store.

In [22]:
import numpy as np
store_wise_cost = np.sum(cost_data, axis=1)
for i in range(len(stores)):
    print(stores[i] + ": " + str(store_wise_cost[i]))

Bengaluru: 1665000
Hyderabad: 1685000
Chennai: 1710000
Mumbai: 2065000
Pune: 1475000


Question 22: Category-Wise Cost

Calculate the total cost incurred for each product category across all stores.

In [23]:
import numpy as np
category_wise_cost = np.sum(cost_data, axis=0)
for i in range(len(categories)):
    print(categories[i] + ": " + str(category_wise_cost[i]))

Electronics: 3250000
Groceries: 1660000
Clothing: 1145000
Furniture: 1045000
Beauty: 665000
Sports: 835000


Question 23: Most Expensive Store

Identify the store with the highest total operating cost.

In [24]:
import numpy as numpy
most_expensive_store = np.argmax(store_wise_cost)
print("Store with the highest total operating cost: ", most_expensive_store)

Store with the highest total operating cost:  3


Question 24: Lowest-Cost Store

Identify the store with the lowest total cost.

In [25]:
import numpy as np
lowest_cost_store = np.argmin(store_wise_cost)
print("Store with the lowest total cost: ", lowest_cost_store)

Store with the lowest total cost:  4


Question 25: Most Expensive Product Category

Determine which product category has the highest total cost across all stores.

In [26]:
import numpy as np
most_expensive_product_category = np.argmax(category_wise_cost)
print("Product category with the highest total cost across all stores: ", most_expensive_product_category)

Product category with the highest total cost across all stores:  0


Part 6: Profit Analysis Using Two Arrays

Question 26: Profit Matrix

Calculate the profit generated for every store and product category.

Use:

profit_data = sales_data - cost_data Display the complete profit matrix.

In [27]:
import numpy as np

sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
profit_data = sales_data - cost_data
print("Profit matrix: ", profit_data)

Profit matrix:  [[210000 105000  90000  70000  65000  65000]
 [190000 110000  85000  85000  70000  70000]
 [220000  95000  95000  65000  65000  60000]
 [260000 120000 110000  95000  85000  85000]
 [160000  95000  75000  55000  60000  60000]]


Question 27: Store-Wise Profit

Calculate the total profit generated by each store.

In [28]:
import numpy as np
stroes_wise_profit = np.sum(profit_data, axis=1)
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
for i in range(len(stores)):
  print(stores[i]+" -"+ str(stroes_wise_profit[i]))

Bengaluru -605000
Hyderabad -610000
Chennai -600000
Mumbai -755000
Pune -505000


Question 28: Category-Wise Profit Calculate the total profit generated by each product category.

In [29]:
import numpy as np
category_wise_profit = np.sum(profit_data, axis=0)
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
for i in range(len(categories)):
  print("Category wise profit: ", categories[i]+" -"+ str(category_wise_profit[i]))

Category wise profit:  Electronics -1040000
Category wise profit:  Groceries -525000
Category wise profit:  Clothing -455000
Category wise profit:  Furniture -370000
Category wise profit:  Beauty -345000
Category wise profit:  Sports -340000


Question 30: Least Profitable Store

Identify the store that generated the lowest total profit.

In [30]:
import numpy as np
least_profitable_store = np.argmin(stroes_wise_profit)
print("Least profitable store: ", stores[least_profitable_store])

Least profitable store:  Pune


Question 31: Most Profitable Category

Find the category with the highest total profit across all stores.

In [31]:
import numpy as np
most_profitable_category = np.argmax(category_wise_profit)
print("Most Profitable Category: ", categories[most_profitable_category])

Most Profitable Category:  Electronics


Question 32: Least Profitable Category

Find the category with the lowest total profit.

In [32]:
import numpy as np
least_profitable_category = np.argmin(category_wise_profit)
print("Least Profitable Category: ", categories[least_profitable_category])

Least Profitable Category:  Sports


Question 33: Maximum Individual Profit

Find the highest profit generated by any single store-category combination.

Display:

Profit amount Store name Product category Use np.unravel_index().

In [33]:
import numpy as np
maximum_individual_profit = np.unravel_index(np.argmax(profit_data), profit_data.shape)
print("Maximum Individual Profit: ", profit_data[maximum_individual_profit])
print("Store Name: ", stores[maximum_individual_profit[0]])
print("Product Category: ", categories[maximum_individual_profit[1]])

Maximum Individual Profit:  260000
Store Name:  Mumbai
Product Category:  Electronics


Question 34: Minimum Individual Profit

Find the smallest profit generated by a store-category combination.

Display the corresponding store and category.

In [34]:
import numpy as np
minimum_individual_profit = np.unravel_index(np.argmin(profit_data), profit_data.shape)
print("Minimum Individual Profit: ", profit_data[minimum_individual_profit])
print("Store Name: ", stores[minimum_individual_profit[0]])
print("Category: ", categories[minimum_individual_profit[1]])

Minimum Individual Profit:  55000
Store Name:  Pune
Category:  Furniture


Part 7: Profit Margin Analysis

Question 35: Profit Margin Matrix

Calculate the profit margin percentage for every store-category combination.

Use:

profit_margin = (profit_data / sales_data) * 100 Round the result to two decimal places.

In [35]:
import numpy as np
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)
print("Profit Margin Matrix: ", profit_margin)

Profit Margin Matrix:  [[24.71 25.   29.03 25.45 34.21 28.89]
 [24.36 23.91 28.81 27.42 33.33 29.17]
 [23.91 24.36 27.94 25.   35.14 27.91]
 [24.76 23.53 29.33 27.54 34.   29.31]
 [23.19 23.46 26.79 24.44 34.29 29.27]]


Question 36: Store-Wise Profit Margin

Calculate the overall profit margin percentage for each store using:

Store Profit Margin = Total Store Profit / Total Store Sales × 100

In [36]:
import numpy as np
total_store_profit = np.sum(profit_data, axis=1)
total_store_sales = np.sum(sales_data, axis=1)
store_wise_profit_margin = total_store_profit / total_store_sales * 100
store_wise_profit_margin = np.round(store_wise_profit_margin, 2)
print("Store-wise Profit Margin: ", store_wise_profit_margin)

Store-wise Profit Margin:  [26.65 26.58 25.97 26.77 25.51]


Question 37: Category-Wise Profit Margin

Calculate the overall profit margin percentage for each product category.

In [37]:
import numpy as np
total_category_profit = np.sum(profit_data, axis=0)
total_category_sales = np.sum(sales_data, axis=0)
category_wise_profit_margin = total_category_profit / total_category_sales * 1
print("category Wise Profit Margin: ", category_wise_profit_margin)

category Wise Profit Margin:  [0.24242424 0.2402746  0.284375   0.2614841  0.34158416 0.2893617 ]


Question 38: Best Store by Profit Margin

Identify the store with the highest overall profit margin.

In [38]:
import numpy as np
best_store_by_profit_margin = np.argmax(store_wise_profit_margin)
print("Best Store by Profit Margin: ", stores[best_store_by_profit_margin])

Best Store by Profit Margin:  Mumbai


Question 39: Best Category by Profit Margin

Identify the product category with the highest profit margin.

In [39]:
import numpy as np
best_category_by_profit_margin = np.argmax(category_wise_profit_margin)
print("Best Category by Profit Margin: ", categories[best_category_by_profit_margin])

Best Category by Profit Margin:  Beauty


Question 40: Low-Margin Transactions

Management considers a profit margin below 22% to be weak.

Find all store-category combinations where the profit margin is below 22%.

Display:

Store Category Sales Cost Profit Profit margin Use Boolean indexing.

In [40]:
import numpy as np
profit_margin = (profit_data / sales_data) * 100
profit_margin = np.round(profit_margin, 2)
low_margin_transactions = profit_margin < 22
print("Low Margin Transactions:")
print(low_margin_transactions)
rows, cols = np.where(low_margin_transactions)
print("\nStore:", stores[rows])
print("Category:", categories[cols])
print("Sales:", sales_data[rows, cols])
print("Cost:", cost_data[rows, cols])
print("Profit:", profit_data[rows, cols])
print("Profit Margin:", profit_margin[rows, cols])

Low Margin Transactions:
[[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]

Store: []
Category: []
Sales: []
Cost: []
Profit: []
Profit Margin: []


Part 8: Boolean Filtering

Question 41: High Sales Values

Find all sales values greater than ₹5,00,000.

In [41]:
import numpy as np
high_sales_values = sales_data[sales_data > 500000]
print("High Sales Values: ", high_sales_values)

High Sales Values:  [ 850000  780000  920000 1050000  510000  690000]


Question 42: Low Sales Values

Find all sales values below ₹2,00,000.

In [42]:
import numpy as np
low_sales_values = sales_data[sales_data > 200000]
print("Low Sales Values: ", low_sales_values)

Low Sales Values:  [ 850000  420000  310000  275000  225000  780000  460000  295000  310000
  210000  240000  920000  390000  340000  260000  215000 1050000  510000
  375000  345000  250000  290000  690000  405000  280000  225000  205000]


Question 43: High Profit Values

Find all store-category combinations where profit is greater than ₹1,50,000.

In [43]:
import numpy as np
high_profit_values = profit_data[profit_data > 150000]
print("High Profit Values: ", high_profit_values)

High Profit Values:  [210000 190000 220000 260000 160000]


Question 44: Moderate Sales Range

Find sales values between ₹2,50,000 and ₹5,00,000.

Use np.logical_and().

In [44]:
import numpy as np
moderate_sales_range = sales_data[np.logical_and(sales_data >= 250000, sales_data >= 500000)]
print("Moderate Sales Range: ", moderate_sales_range)

Moderate Sales Range:  [ 850000  780000  920000 1050000  510000  690000]


Question 45: Premium Performance

A store-category combination is considered premium when:

Sales are greater than ₹5,00,000 Profit is greater than ₹1,50,000 Find all premium-performing combinations.

In [45]:
import numpy as np
sales_greater_than_500000 = sales_data > 500000
profit_greater_than_150000 = profit_data > 150000
premium_performing_combinations = sales_greater_than_500000 + profit_greater_than_150000
print("Premium Performing Combinations: ", premium_performing_combinations)

Premium Performing Combinations:  [[ True False False False False False]
 [ True False False False False False]
 [ True False False False False False]
 [ True  True False False False False]
 [ True False False False False False]]


Question 46: Underperforming Combinations

A store-category combination is considered underperforming when:

Sales are below ₹2,50,000 Profit margin is below 25% Find all such combinations.

In [46]:
import numpy as np
sales_below_250000 = sales_data < 250000
profit_margin_below_25 = profit_margin < 25
underperforming_combinations = sales_below_250000 + profit_margin_below_25
print("Underperforming Combinations: ", underperforming_combinations)

Underperforming Combinations:  [[ True False False False  True  True]
 [ True  True False False  True  True]
 [ True  True False False  True  True]
 [ True  True False False False False]
 [ True  True False  True  True  True]]


Question 47: Category Performance Classification

Create a new array that classifies every sales value as:

"High" when sales are at least ₹5,00,000 "Medium" when sales are between ₹2,50,000 and ₹4,99,999 "Low" when sales are below ₹2,50,000 Use np.where() or np.select().

In [47]:
import numpy as np
sales_classification = np.where(sales_data >= 500000, "High", np.where(sales_data >= 250000, "Medium", "Low"))
print("Sales Classification: ", sales_classification)

Sales Classification:  [['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'Medium' 'Medium' 'Medium' 'Low' 'Low']
 ['High' 'High' 'Medium' 'Medium' 'Medium' 'Medium']
 ['High' 'Medium' 'Medium' 'Low' 'Low' 'Low']]


Part 9: Target-Based Analysis

Use the following category-wise monthly sales targets:

sales_targets = np.array([ 800000, # Electronics 450000, # Groceries 320000, # Clothing 300000, # Furniture 200000, # Beauty 230000 # Sports ])

In [48]:
import numpy as np
sales_targets = np.array([
    800000,  # Electronics
    450000,  # Groceries
    320000,  # Clothing
    300000,  # Furniture
    200000,  # Beauty
    230000   # Sports
])
print("Category Wise Monthly Sales Targets: ", sales_targets)

Category Wise Monthly Sales Targets:  [800000 450000 320000 300000 200000 230000]


Question 48: Target Comparison Compare every store’s category sales against sales_targets.

Use NumPy broadcasting.

In [49]:
import numpy as np
target_comparison = sales_data >= sales_targets
print("Target Comparison: ", target_comparison)

Target Comparison:  [[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 49: Target Achievement Matrix

Create a Boolean array where:

True means the store achieved the category target False means the store failed to achieve the target

In [50]:
import numpy as np
target_status = sales_data >= sales_targets
print("target_status: ", target_status)

target_status:  [[ True False False False False False]
 [False  True False  True  True  True]
 [ True False  True False False False]
 [ True  True  True  True  True  True]
 [False False False False False False]]


Question 50: Target Achievement Count

Calculate the number of categories in which each store achieved its target.

In [51]:
import numpy as np
target_achivement_count = np.sum(target_status, axis=1)
print("Target Achievement Count: ", target_achivement_count)

Target Achievement Count:  [1 4 2 6 0]


Question 51: Best Target-Performing Store

Find the store that achieved the highest number of category targets.

In [52]:
import numpy as np
targer_achivement_count = np.sum(target_status, axis=1)
best_target_performing_store = np.argmax(target_achivement_count)
print("Best Target-Performing Store: ", stores[best_target_performing_store])

Best Target-Performing Store:  Mumbai


Question 52: Target Achievement by Category

Calculate how many stores achieved the target for each product category.

In [53]:
import numpy as np
target_achivement_category = np.sum(target_status, axis=0)
print("Target Achivement By Category: ", target_achivement_category)

Target Achivement By Category:  [3 2 2 2 2 2]


Question 53: Sales Target Variance

Calculate the difference between actual sales and target sales for every store.

Use:

Variance = Actual Sales - Target Sales

In [54]:
import numpy as np
actual_sales = sales_data
target_sales = sales_targets
variance = actual_sales - target_sales
print("Variance: ", variance)

Variance:  [[  50000  -30000  -10000  -25000  -10000   -5000]
 [ -20000   10000  -25000   10000   10000   10000]
 [ 120000  -60000   20000  -40000  -15000  -15000]
 [ 250000   60000   55000   45000   50000   60000]
 [-110000  -45000  -40000  -75000  -25000  -25000]]


Question 55: Stores Missing Electronics Target

Identify stores that failed to achieve the Electronics sales target.

In [55]:
import numpy as np
electronics_target = sales_targets[0]
stores_missing_electronics_target = np.where(sales_data[:, 0] < electronics_target)[0]
print("Stores Missing Electronics Target: ", stores_missing_electronics_target)

Stores Missing Electronics Target:  [1 4]


Question 56: Stores Achieving All Targets

Check whether any store achieved its target in all six product categories.

Use np.all().

In [56]:
import numpy as np
store_Achieving_all_targets = np.all(target_status, axis=1)
print("Achived Targets: ", store_Achieving_all_targets)

Achived Targets:  [False False False  True False]


Question 57: Stores Achieving At Least One Target

Identify stores that achieved at least one category target.

Use np.any().

In [57]:
import numpy as np
stores_achieving_target = np.any(target_status, axis=1)
print("Stores Achieving At Least One Target: ", stores_achieving_target)

Stores Achieving At Least One Target:  [ True  True  True  True False]


Part 10: Discount Scenario

SmartMart plans to offer category-wise discounts:

discount_rates = np.array([ 0.10, # Electronics: 10% 0.05, # Groceries: 5% 0.15, # Clothing: 15% 0.12, # Furniture: 12% 0.08, # Beauty: 8% 0.10 # Sports: 10% ])

Question 58: Discount Amount Matrix Calculate the discount amount for each store-category combination.

Use broadcasting.

In [58]:
import numpy as np
discount_rates = np.array([
    0.10,  # Electronics: 10%
    0.05,  # Groceries: 5%
    0.15,  # Clothing: 15%
    0.12,  #Furniture: 12%
    0.08,  #Beauty: 8%
    0.10, #Sports 10%
])
print("Discount Rates: ", discount_rates)

Discount Rates:  [0.1  0.05 0.15 0.12 0.08 0.1 ]


Question 59: Sales After Discount

Calculate the net sales value after applying the category-wise discounts.

In [59]:
import numpy as np
discount_amount = sales_data * discount_rates
net_sales = sales_data - discount_amount
print("Net Sales: ", net_sales)

Net Sales:  [[765000. 399000. 263500. 242000. 174800. 202500.]
 [702000. 437000. 250750. 272800. 193200. 216000.]
 [828000. 370500. 289000. 228800. 170200. 193500.]
 [945000. 484500. 318750. 303600. 230000. 261000.]
 [621000. 384750. 238000. 198000. 161000. 184500.]]


Question 60: Profit After Discount

Assuming costs remain unchanged, calculate the new profit after the discounts are applied.

In [60]:
import numpy as np
profit = net_sales - cost_data
print("Profit: ", profit)

Profit:  [[125000.  84000.  43500.  37000.  49800.  42500.]
 [112000.  87000.  40750.  47800.  53200.  46000.]
 [128000.  75500.  44000.  33800.  50200.  38500.]
 [155000.  94500.  53750.  53600.  65000.  56000.]
 [ 91000.  74750.  33000.  28000.  46000.  39500.]]


Question 61: Profit Margin After Discount

Calculate the new profit margin after applying discounts.

In [61]:
import numpy as np
profit_margin = (profit / net_sales) * 100
print("Profit Margin: ", profit_margin)

Profit Margin:  [[16.33986928 21.05263158 16.5085389  15.2892562  28.48970252 20.98765432]
 [15.95441595 19.90846682 16.25124626 17.52199413 27.53623188 21.2962963 ]
 [15.4589372  20.37786775 15.22491349 14.77272727 29.4947121  19.89664083]
 [16.4021164  19.50464396 16.8627451  17.65480896 28.26086957 21.4559387 ]
 [14.65378422 19.42820013 13.86554622 14.14141414 28.57142857 21.40921409]]


Question 62: Loss-Making Transactions

Check whether any store-category combination becomes loss-making after discounts.

Display the affected store and category names.

In [62]:
import numpy as np
loss_making_transactions = profit < 0
print("Loss-Making Transactions: ", loss_making_transactions)
affected_stores = np.where(loss_making_transactions)[0]
affected_categories_names = np.where(loss_making_transactions)[1]
print("Affected Stores: ", affected_stores)
print("Affected Categories: ", affected_categories_names)

Loss-Making Transactions:  [[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]]
Affected Stores:  []
Affected Categories:  []


Question 63: Discount Impact

Calculate how much total revenue the company loses because of the proposed discounts.

In [63]:
import numpy as np
discount_impact = np.sum(sales_data * discount_rates)
print("Discount Impact: ", discount_impact)

Discount Impact:  1146350.0


Question 64: Store Most Affected by Discounts

Identify the store that loses the highest amount of revenue due to discounts.

In [64]:
import numpy as np
discount_impact = np.sum(sales_data * discount_rates, axis=1)
store_most_affected_by_discounts = np.argmax(discount_impact)
print("Store Most Affected by Discounts: ", stores[store_most_affected_by_discounts])

Store Most Affected by Discounts:  Mumbai


Part 11: Tax and Price Adjustment

The government introduces category-wise tax rates:

tax_rates = np.array([ 0.18, 0.05, 0.12, 0.18, 0.18, 0.12 ])

Question 65: Tax Collection Matrix

Calculate the tax collected on sales for each store and category.

In [65]:
import numpy as np
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
tax_rates = np.array([
    0.18,
    0.05,
    0.12,
    0.18,
    0.18,
    0.12
])
tax_collection = sales_data * tax_rates
print(tax_collection)

[[153000.  21000.  37200.  49500.  34200.  27000.]
 [140400.  23000.  35400.  55800.  37800.  28800.]
 [165600.  19500.  40800.  46800.  33300.  25800.]
 [189000.  25500.  45000.  62100.  45000.  34800.]
 [124200.  20250.  33600.  40500.  31500.  24600.]]


Question 66: Sales Including Tax

Calculate the final customer billing value after adding tax.

In [66]:
import numpy as np
sales_including_tax = sales_data + tax_collection
customer_billing_value = sales_including_tax
print("Customer Billing Value After Adding Tax: ", customer_billing_value)

Customer Billing Value After Adding Tax:  [[1003000.  441000.  347200.  324500.  224200.  252000.]
 [ 920400.  483000.  330400.  365800.  247800.  268800.]
 [1085600.  409500.  380800.  306800.  218300.  240800.]
 [1239000.  535500.  420000.  407100.  295000.  324800.]
 [ 814200.  425250.  313600.  265500.  206500.  229600.]]


Question 67: Store-Wise Tax Collection

Calculate the total tax collected by each store.

In [67]:
import numpy as np
store_wise_tax_collection = np.sum(tax_collection, axis=1)
print("Store-Wise Tax Collection: ", store_wise_tax_collection)

Store-Wise Tax Collection:  [321900. 321200. 331800. 401400. 274650.]


Question 68: Category-Wise Tax Collection

Calculate total tax collected for each category.

In [68]:
import numpy as np
category_wise_tax_collection = np.sum(tax_collection, axis=0)
print("Category-Wise Tax Collection: ", category_wise_tax_collection)

Category-Wise Tax Collection:  [772200. 109250. 192000. 254700. 181800. 141000.]


Question 69: Highest Tax-Contributing Store

Identify the store that contributes the highest tax amount.

In [69]:
import numpy as np
highest_tax_contributing_store = np.argmax(store_wise_tax_collection)
print("Highest Tax-Contributing Store: ", stores[highest_tax_contributing_store])

Highest Tax-Contributing Store:  Mumbai


Part 12: Array Modification
` Question 70: Updated Pune Electronics Sales

The Pune store reports that its Electronics sales were entered incorrectly.

Update Pune Electronics sales from ₹6,90,000 to ₹7,40,000.

Make the change in a copied array without modifying the original array.

In [70]:
import numpy as np
pune_electronics_sales = sales_data[1, 0]
updated_pune_electronics_sales = np.copy(sales_data)
updated_pune_electronics_sales[1, 0] = 740000
print("Original Sales Data: ", sales_data)
print("Updated Pune Electronics Sales: ", updated_pune_electronics_sales)

Original Sales Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Updated Pune Electronics Sales:  [[ 850000  420000  310000  275000  190000  225000]
 [ 740000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]


Question 71: Revised Beauty Cost

Due to supplier negotiations, Beauty product costs are reduced by 8% for all stores.

Create an updated cost array.

In [71]:
import numpy as np
reduced_cost = cost_data * 0.92
print("Reduced Cost: ", reduced_cost)

Reduced Cost:  [[588800. 289800. 202400. 188600. 115000. 147200.]
 [542800. 322000. 193200. 207000. 128800. 156400.]
 [644000. 271400. 225400. 179400. 110400. 142600.]
 [726800. 358800. 243800. 230000. 151800. 188600.]
 [487600. 285200. 188600. 156400. 105800. 133400.]]


Question 72: Furniture Cost Increase

Furniture costs increase by 12% for all stores.

Update only the Furniture column.

In [72]:
import numpy as np
Furniture_cost_increase = cost_data * 1.12
print("Furniture Cost Increase: ", Furniture_cost_increase)

Furniture Cost Increase:  [[716800. 352800. 246400. 229600. 140000. 179200.]
 [660800. 392000. 235200. 252000. 156800. 190400.]
 [784000. 330400. 274400. 218400. 134400. 173600.]
 [884800. 436800. 296800. 280000. 184800. 229600.]
 [593600. 347200. 229600. 190400. 128800. 162400.]]


Question 73: Store Closure Simulation

Assume the Pune store is temporarily closed.

Remove Pune’s sales and cost data from the analysis using np.delete().

In [73]:
import numpy as np
updated_sales_data = np.delete(sales_data, 1, axis=0)
updated_cost_data = np.delete(cost_data, 1, axis=0)
print("Updated Sales Data: ", updated_sales_data)
print("Updated Cost Data: ", updated_cost_data)

Updated Sales Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]]
Updated Cost Data:  [[640000 315000 220000 205000 125000 160000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]


Question 74: Adding a New Store

A new Delhi store is opened with the following data:

delhi_sales = np.array([ 880000, 475000, 330000, 290000, 215000, 250000 ])

delhi_cost = np.array([ 665000, 360000, 235000, 215000, 145000, 180000 ]) Add Delhi to both arrays using np.vstack().

Also add "Delhi" to the stores array.

In [74]:
import numpy as np
delhi_sales = np.array([
    880000, 475000, 330000, 290000, 215000, 250000
])
delhi_cost = np.array([
    665000, 360000, 235000, 215000, 145000, 180000
])
updated_sales_data = np.vstack((sales_data, delhi_sales))
updated_cost_data = np.vstack((cost_data, delhi_cost))
stores = np.append(stores, "Delhi")
print("Updated Sales Data: ", updated_sales_data)
print("Updated Cost Data: ", updated_cost_data)
print("Stores: ", stores)

Updated Sales Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 880000  475000  330000  290000  215000  250000]]
Updated Cost Data:  [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]
 [665000 360000 235000 215000 145000 180000]]
Stores:  ['Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai' 'Pune' 'Delhi']


Question 75: Adding a New Product Category

SmartMart starts selling Home Appliances.

home_appliance_sales = np.array([ 360000, 325000, 390000, 420000, 295000 ])

home_appliance_cost = np.array([ 265000, 240000, 285000, 305000, 225000 ]) Add the new category as a column using np.column_stack() or np.hstack().

In [75]:
import numpy as np
home_appliance_sales = np.array([
    360000,
    325000,
    390000,
    420000,
    295000
])
home_appliance_cost = np.array([
    265000,
    240000,
    285000,
    305000,
    225000
])
updated_sales_data = np.column_stack((sales_data, home_appliance_sales))
updated_cost_data = np.column_stack((cost_data, home_appliance_cost))
print("Updated Sales Data: ", updated_sales_data)
print("Updated Cost Data: ", updated_cost_data)

Updated Sales Data:  [[ 850000  420000  310000  275000  190000  225000  360000]
 [ 780000  460000  295000  310000  210000  240000  325000]
 [ 920000  390000  340000  260000  185000  215000  390000]
 [1050000  510000  375000  345000  250000  290000  420000]
 [ 690000  405000  280000  225000  175000  205000  295000]]
Updated Cost Data:  [[640000 315000 220000 205000 125000 160000 265000]
 [590000 350000 210000 225000 140000 170000 240000]
 [700000 295000 245000 195000 120000 155000 285000]
 [790000 390000 265000 250000 165000 205000 305000]
 [530000 310000 205000 170000 115000 145000 225000]]


Part 13: Sorting and Ranking

Question 76: Sort Stores by Sales

Sort stores in ascending order based on total sales.

Display store names and sales totals.

In [76]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
sorted_indices = np.argsort(total_sales)
sorted_stores = stores[sorted_indices]
sorted_sales = total_sales[sorted_indices]
print("Sorted Stores: ", sorted_stores)
print("Sorted Sales: ", sorted_sales)
print("Store Names and Sales Totals: ", list(zip(sorted_stores, sorted_sales)))

Sorted Stores:  ['Pune' 'Bengaluru' 'Hyderabad' 'Chennai' 'Mumbai']
Sorted Sales:  [1980000 2270000 2295000 2310000 2820000]
Store Names and Sales Totals:  [(np.str_('Pune'), np.int64(1980000)), (np.str_('Bengaluru'), np.int64(2270000)), (np.str_('Hyderabad'), np.int64(2295000)), (np.str_('Chennai'), np.int64(2310000)), (np.str_('Mumbai'), np.int64(2820000))]


Question 77: Rank Stores by Profit

Rank stores from highest to lowest total profit.

Use np.argsort().

In [77]:
import numpy as np
profit = sales_data - cost_data
total_profit = np.sum(profit, axis=1)
sorted_indices = np.argsort(total_profit)[::-1]
ranked_stores = stores[sorted_indices]
ranked_profits = total_profit[sorted_indices]
print("Ranked Stores: ", ranked_stores)
print("Ranked Profits: ", ranked_profits)

Ranked Stores:  ['Mumbai' 'Hyderabad' 'Bengaluru' 'Chennai' 'Pune']
Ranked Profits:  [755000 610000 605000 600000 505000]


Question 78: Sort Categories by Revenue

Sort product categories from highest to lowest total revenue.

In [78]:
import numpy as np
total_revenue = np.sum(sales_data, axis=0)
sorted_indices = np.argsort(total_revenue)[::-1]
sorted_categories = categories[sorted_indices]
sorted_revenue = total_revenue[sorted_indices]
print("Sorted Categories: ", sorted_categories)
print("Sorted Revenue: ", sorted_revenue)

Sorted Categories:  ['Electronics' 'Groceries' 'Clothing' 'Furniture' 'Sports' 'Beauty']
Sorted Revenue:  [4290000 2185000 1600000 1415000 1175000 1010000]


Question 79: Top Three Store-Category Sales

Find the three highest individual sales values in the complete sales matrix.

Display their:

Sales value Store name Category name

In [79]:
import numpy as np
top_three_stores = np.sort(sales_data.flatten())[-3:]
top_three_indices = np.argsort(sales_data.flatten())[-3:]
top_three_stores_names = stores[top_three_indices // sales_data.shape[1]]
top_three_categories_names = categories[top_three_indices % sales_data.shape[1]]
print("Top Three Store-Category Sales: ", top_three_stores)
print("Top Three Store Names: ", top_three_stores_names)
print("Top Three Category Names: ", top_three_categories_names)

Top Three Store-Category Sales:  [ 850000  920000 1050000]
Top Three Store Names:  ['Bengaluru' 'Chennai' 'Mumbai']
Top Three Category Names:  ['Electronics' 'Electronics' 'Electronics']


Question 80: Bottom Three Profits

Find the three lowest profit values in the profit matrix.

In [80]:
import numpy as np
bottom_three_profits = np.sort(profit.flatten())[:3]
bottom_three_indices = np.argsort(profit.flatten())[:3]
bottom_three_stores_names = stores[bottom_three_indices // profit.shape[1]]
bottom_three_categories_names = categories[bottom_three_indices % profit.shape [1]]
print("Bottom Three Profits: ", bottom_three_profits)
print("Bottom Three Store Names: ", bottom_three_stores_names)
print("Bottom Three Category Names: ", bottom_three_categories_names)

Bottom Three Profits:  [55000 60000 60000]
Bottom Three Store Names:  ['Pune' 'Pune' 'Chennai']
Bottom Three Category Names:  ['Furniture' 'Sports' 'Sports']


Part 14: Statistical Analysis

Question 81: Sales Statistics

Calculate the following for the complete sales array:

Minimum Maximum Mean Median Standard deviation Variance 25th percentile 50th percentile 75th percentil

In [81]:
import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
mean_sales = np.mean(sales_data)
median_sales = np.median(sales_data)
std_sales = np.std(sales_data)
var_sales = np.var(sales_data)
percentile_25 = np.percentile(sales_data, 25)
percentile_50 = np.percentile(sales_data, 50)
percentile_75 = np.percentile(sales_data, 75)
print("Minimum Sales: ", min_sales)
print("Maximum Sales: ", max_sales)
print("Mean Sales: ", mean_sales)
print("Median Sales: ", median_sales)
print("Standard Deviation of Sales: ", std_sales)
print("Variance of Sales: ", var_sales)
print("25th Percentile of Sales: ", percentile_25)
print("50th Percentile of Sales: ", percentile_50)
print("75th Percentile of Sales: ", percentile_75)

Minimum Sales:  175000
Maximum Sales:  1050000
Mean Sales:  389166.6666666667
Median Sales:  302500.0
Standard Deviation of Sales:  230322.53954448793
Variance of Sales:  53048472222.222206
25th Percentile of Sales:  228750.0
50th Percentile of Sales:  302500.0
75th Percentile of Sales:  416250.0


Question 82: Store-Wise Standard Deviation

Calculate the sales standard deviation for every store.

Use this value to determine which store has the most variation between product categories.

In [82]:
import numpy as np
std_deviation_stores = np.std(sales_data, axis=1)
most_varied_store_index = np.argmax(std_deviation_stores)
most_varied_store = stores[most_varied_store_index]
print("Standard Deviation of Stores: ", std_deviation_stores)
print("Most Varied Store: ", most_varied_store)
print("Store with the Most Variation: ", most_varied_store)

Standard Deviation of Stores:  [223059.53365762 194502.5706771  249265.58794453 271860.87128039
 177200.45146669]
Most Varied Store:  Mumbai
Store with the Most Variation:  Mumbai


Question 83: Category-Wise Standard Deviation

Determine which product category has the highest variation in sales across stores.

In [83]:
import numpy as np
std_deviation_categories = np.std(sales_data, axis=0)
most_varied_category_index = np.argmax(std_deviation_categories)
most_varied_category = categories[most_varied_category_index]
print("Standard Deviation of Categories: ", std_deviation_categories)
print("Most Varied Category: ", most_varied_category)

Standard Deviation of Categories:  [122539.78945632  43312.81565542  33911.64991563  41303.75285613
  26570.66051117  29832.86778035]
Most Varied Category:  Electronics


print("Most Varied Category Index:" , most_varied_category_index)

Calculate the company-wide average sales value.

Count how many store-category sales values are above this average.

In [84]:
import numpy as np
company_wide_average_sales = np.mean(sales_data)
above_average_count = np.sum(sales_data > company_wide_average_sales)
print("Company-Wide Average Sales: ", company_wide_average_sales)
print("Above Average Count: ", above_average_count)

Company-Wide Average Sales:  389166.6666666667
Above Average Count:  10


Question 85: Outlier Detection

Treat any sales value greater than:

Mean + 1.5 × Standard Deviation as a high-value outlier.

Identify all such sales values.

In [85]:
import numpy as np
high_value_outliers = sales_data[sales_data > (np.mean(sales_data) + 1.5 * np.std(sales_data))]
print("High-Value Outliers: ", high_value_outliers)

High-Value Outliers:  [ 850000  780000  920000 1050000]


Part 15: Reshaping and Transformation

Question 86: Flatten Sales Data

Convert the two-dimensional sales array into a one-dimensional array using:

flatten() ravel() Explain the difference between the two methods.

In [86]:
import numpy as np
flattened_sales_data = sales_data.flatten()
print("Flattened Sales Data: ", flattened_sales_data)

Flattened Sales Data:  [ 850000  420000  310000  275000  190000  225000  780000  460000  295000
  310000  210000  240000  920000  390000  340000  260000  185000  215000
 1050000  510000  375000  345000  250000  290000  690000  405000  280000
  225000  175000  205000]


Question 87: Reshape Sales Data

Reshape the 5 × 6 sales array into:

3 × 10 10 × 3 2 × 15 15 × 2 Verify that no data is lost

In [87]:
import numpy as np
reshaped_sales_data_1 = sales_data.reshape(3, 10)
reshaped_sales_data_2 = sales_data.reshape(10, 3)
reshaped_sales_data_3 = sales_data.reshape(2, 15)
reshaped_sales_data_4 = sales_data.reshape(15, 2)
print("Reshaped Sales Data 1: ", reshaped_sales_data_1)
print("Reshaped Sales Data 2: ", reshaped_sales_data_2)
print("Reshaped Sales Data 3: ", reshaped_sales_data_3)
print("Reshaped Sales Data 4: ", reshaped_sales_data_4)

Reshaped Sales Data 1:  [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000]
 [ 210000  240000  920000  390000  340000  260000  185000  215000 1050000
   510000]
 [ 375000  345000  250000  290000  690000  405000  280000  225000  175000
   205000]]
Reshaped Sales Data 2:  [[ 850000  420000  310000]
 [ 275000  190000  225000]
 [ 780000  460000  295000]
 [ 310000  210000  240000]
 [ 920000  390000  340000]
 [ 260000  185000  215000]
 [1050000  510000  375000]
 [ 345000  250000  290000]
 [ 690000  405000  280000]
 [ 225000  175000  205000]]
Reshaped Sales Data 3:  [[ 850000  420000  310000  275000  190000  225000  780000  460000  295000
   310000  210000  240000  920000  390000  340000]
 [ 260000  185000  215000 1050000  510000  375000  345000  250000  290000
   690000  405000  280000  225000  175000  205000]]
Reshaped Sales Data 4:  [[ 850000  420000]
 [ 310000  275000]
 [ 190000  225000]
 [ 780000  460000]
 [ 295000  310000]
 [ 210000  240000]
 [ 920000  3

Question 88: Transpose Sales Data

Transpose the sales array so that:

Rows represent product categories Columns represent stores Display the new shape.

In [88]:
import numpy as np
transposed_sales_data = sales_data.T
print("Transposed Sales Data: ", transposed_sales_data)
print("Transposed Sales Data Shape: ", transposed_sales_data.shape)

Transposed Sales Data:  [[ 850000  780000  920000 1050000  690000]
 [ 420000  460000  390000  510000  405000]
 [ 310000  295000  340000  375000  280000]
 [ 275000  310000  260000  345000  225000]
 [ 190000  210000  185000  250000  175000]
 [ 225000  240000  215000  290000  205000]]
Transposed Sales Data Shape:  (6, 5)


Question 89: Combined Sales and Cost Array

Stack sales_data and cost_data vertically.

Display the resulting shape.

In [89]:
import numpy as np
combined_sales_cost_data = np.vstack((sales_data, cost_data))
print("Combined Sales and Cost Data: ", combined_sales_cost_data)
print("Combined Sales and Cost Data Shape: ", combined_sales_cost_data.shape)

Combined Sales and Cost Data:  [[ 850000  420000  310000  275000  190000  225000]
 [ 780000  460000  295000  310000  210000  240000]
 [ 920000  390000  340000  260000  185000  215000]
 [1050000  510000  375000  345000  250000  290000]
 [ 690000  405000  280000  225000  175000  205000]
 [ 640000  315000  220000  205000  125000  160000]
 [ 590000  350000  210000  225000  140000  170000]
 [ 700000  295000  245000  195000  120000  155000]
 [ 790000  390000  265000  250000  165000  205000]
 [ 530000  310000  205000  170000  115000  145000]]
Combined Sales and Cost Data Shape:  (10, 6)


Question 90: Store-Level Combined Data

Create a three-dimensional array where:

First layer contains sales data Second layer contains cost data Use np.stack().

Display the shape of the new array.

In [90]:
import numpy as np
store_level_combined_data = np.stack((sales_data, cost_data), axis=0)
print("Store-Level Combined Data: ", store_level_combined_data)
print("Store-Level Combined Data Shape: ", store_level_combined_data.shape)

Store-Level Combined Data:  [[[ 850000  420000  310000  275000  190000  225000]
  [ 780000  460000  295000  310000  210000  240000]
  [ 920000  390000  340000  260000  185000  215000]
  [1050000  510000  375000  345000  250000  290000]
  [ 690000  405000  280000  225000  175000  205000]]

 [[ 640000  315000  220000  205000  125000  160000]
  [ 590000  350000  210000  225000  140000  170000]
  [ 700000  295000  245000  195000  120000  155000]
  [ 790000  390000  265000  250000  165000  205000]
  [ 530000  310000  205000  170000  115000  145000]]]
Store-Level Combined Data Shape:  (2, 5, 6)


Part 16: Missing Data Scenario

The company discovers that some sales values were not recorded.

sales_with_missing = np.array([ [850000, 420000, np.nan, 275000, 190000, 225000], [780000, 460000, 295000, np.nan, 210000, 240000], [920000, 390000, 340000, 260000, 185000, 215000], [1050000, np.nan, 375000, 345000, 250000, 290000], [690000, 405000, 280000, 225000, np.nan, 205000] ])

In [91]:
import numpy as np
sales_with_missing = np.array([
    [850000, 420000, np.nan, 275000, 190000, 225000],
    [780000, 460000, 295000, np.nan, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, np.nan, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, np.nan, 205000]
    ])
print(sales_with_missing)

[[ 850000.  420000.      nan  275000.  190000.  225000.]
 [ 780000.  460000.  295000.      nan  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.      nan  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.      nan  205000.]]


Question 91: Missing Value Detection

Find:

Total number of missing values Location of missing values Stores and categories containing missing values

In [92]:
import numpy as np
total_number_of_missing_values = np.sum(np.isnan(sales_with_missing))
location_of_missing_values = np.where(np.isnan(sales_with_missing))
stores_with_missing_values = np.unique(location_of_missing_values[0])
categories_with_missing_values = np.unique(location_of_missing_values[1])
print("Total Number of Missing Values: ", total_number_of_missing_values)
print("Location of Missing Values: ", list(zip(location_of_missing_values[0], location_of_missing_values[1])))
print("Stores with Missing Values: ", stores_with_missing_values)
print("Categories with Missing Values: ", categories_with_missing_values)

Total Number of Missing Values:  4
Location of Missing Values:  [(np.int64(0), np.int64(2)), (np.int64(1), np.int64(3)), (np.int64(3), np.int64(1)), (np.int64(4), np.int64(4))]
Stores with Missing Values:  [0 1 3 4]
Categories with Missing Values:  [1 2 3 4]


Question 92: Replace Missing Values with Zero

Replace all missing sales values with zero.

In [93]:
import numpy as np
sales_with_missing[np.isnan(sales_with_missing)] = 0
print("Sales with Missing Values Replaced with Zero: ", sales_with_missing)

Sales with Missing Values Replaced with Zero:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 93: Replace with Company Average

Replace missing values with the overall average of available sales values.

Use np.nanmean().

In [94]:
import numpy as np
average_sales = np.nanmean(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = average_sales
print("Sales with Missing Values Replaced with Company Average: ", sales_with_missing)

Sales with Missing Values Replaced with Company Average:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 94: Replace with Category Average

Replace each missing value with the average sales value of its respective product category.

In [95]:
import numpy as np
category_averages = np.nanmean(sales_with_missing, axis=0)
sales_with_missing[np.isnan(sales_with_missing)] = np.take(category_averages, np.where(np.isnan(sales_with_missing))[1])
print("Sales with Missing Values Replaced with Category Averages: ", sales_with_missing)

Sales with Missing Values Replaced with Category Averages:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


Question 95: Missing Value Impact

Compare total sales before and after replacing missing values with zero.

In [96]:
import numpy as np
total_sales_before = np.sum(sales_with_missing)
sales_with_missing[np.isnan(sales_with_missing)] = 0
total_sales_after = np.sum(sales_with_missing)
print("Total Sales Before Replacing Missing Values with Zero: ", total_sales_before)
print("Total Sales After Replacing Missing Values with Zero: ", total_sales_after)
print("Total Sales Before Replacing Missing Values with Zero: ", total_sales_before)
print("Total Sales After Replacing Missing Values with Zero: ", total_sales_after)

Total Sales Before Replacing Missing Values with Zero:  10370000.0
Total Sales After Replacing Missing Values with Zero:  10370000.0
Total Sales Before Replacing Missing Values with Zero:  10370000.0
Total Sales After Replacing Missing Values with Zero:  10370000.0


Part 17: Conditional Business Decisions

Question 96: Store Performance Labels

Classify each store based on total sales:

"Excellent": Total sales above ₹28,00,000 "Good": Total sales between ₹24,00,000 and ₹28,00,000 "Needs Improvement": Total sales below ₹24,00,000 Use np.select().

In [97]:
import numpy as np
sales_data = sales_with_missing
print(sales_data)

[[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]


In [98]:
import numpy as np
total_sales = np.nansum(sales_data, axis=1)
conditions = [
    total_sales > 2800000,
    (total_sales >= 2400000) & (total_sales <= 2800000),
    total_sales < 2400000,
]
choices = ["Excellent", "Good", "Needs Improvement"]
store_performance_labels = np.select(conditions, choices, default="Not Classified")
print("Store Performance Labels: ", store_performance_labels)


Store Performance Labels:  ['Needs Improvement' 'Needs Improvement' 'Needs Improvement'
 'Needs Improvement' 'Needs Improvement']


Question 97: Profitability Classification

Classify each store-category combination as:

"Highly Profitable": Profit above ₹2,00,000 "Profitable": Profit between ₹1,00,000 and ₹2,00,000 "Low Profit": Profit below ₹1,00,000 "Loss": Profit below zero

In [99]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
conditions = [
    profit > 200000,
    (profit >= 100000) & (profit <= 200000),
    profit < 100000,
    profit < 0,
]
choices = ["Highly Profitable", "Profitable", "Low Profit", "Loss"]
profitability_classification = np.select(conditions, choices, default="Not Classified")
print("Profitability Classification: ", profitability_classification)

Profitability Classification:  ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
 'Highly Profitable' 'Highly Profitable']


Question 98: Expansion Recommendation

A store is eligible for expansion when:

Total sales are above ₹25,00,000 Total profit is above ₹7,00,000 Overall profit margin is above 25% Identify eligible stores.

In [100]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
overall_profit_margin = np.mean(profit / total_sales)
conditions = [
    profit < 0,
    profit < 100000,
    profit <= 200000,
    profit > 200000
]
choices = ["Loss", "Low Profit", "Profitable", "Highly Profitable"]
profitability_classification = np.select(conditions, choices, default="Not Classified")
print("Profitability Classification: ", profitability_classification)

Profitability Classification:  ['Highly Profitable' 'Highly Profitable' 'Highly Profitable'
 'Highly Profitable' 'Highly Profitable']


Question 99: Category Promotion Recommendation

A product category should receive additional promotion when:

Average sales are below ₹3,00,000 Profit margin is above 25% Identify the categories that satisfy these conditions.

In [101]:
import numpy as np
average_sales = np.mean(sales_data, axis=0)
total_sales = np.sum(sales_data, axis=0)
total_cost = np.sum(cost_data, axis=0)
profit = total_sales - total_cost
profit_margin = profit / total_sales
conditions = [
    average_sales < 300000,
    profit_margin <= 0.25,
    profit_margin > 0.25,
]
choices = ["Low Sales", "Low Profit Margin", "High Profit Margin"]
category_promotion_recommendation = np.select(conditions, choices, default="Not Recommended")
print("Category Promotion Recommendation: ", category_promotion_recommendation)

Category Promotion Recommendation:  ['Low Profit Margin' 'Low Profit Margin' 'Low Sales' 'Low Sales'
 'Low Sales' 'Low Sales']


Question 100: Cost Optimization Recommendation

Find store-category combinations where:

Cost is greater than ₹2,50,000 Profit margin is below 25% These combinations should be reviewed for cost optimization.

In [102]:
import numpy as np
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
profit_margin = profit / total_sales
conditions = [
    total_cost > 250000,
    profit_margin < 0.25,
    profit_margin >= 0.25,
]
choices = ["High Cost", "Low Profit Margin", "High Profit Margin"]
cost_optimization_recommendation = np.select(conditions, choices, default="Not Recommended")
print("Cost Optimization Recommendation: ", cost_optimization_recommendation)

Cost Optimization Recommendation:  ['High Cost' 'High Cost' 'High Cost' 'High Cost' 'High Cost']


Part 18: Inventory Scenario

Use the following inventory arrays:

In [103]:
import numpy as np
opening_stock = np.array([
    [120, 450, 300, 90, 250, 180],
    [110, 500, 280, 100, 270, 200],
    [130, 420, 320, 85, 240, 170],
    [150, 550, 350, 120, 300, 220],
    [100, 400, 260, 75, 220, 160]
])

units_sold = np.array([
    [95, 380, 240, 65, 190, 140],
    [85, 420, 230, 75, 210, 155],
    [105, 350, 270, 60, 180, 130],
    [125, 470, 295, 90, 235, 175],
    [75, 330, 205, 55, 165, 120]
])

print(opening_stock)
print(units_sold)

[[120 450 300  90 250 180]
 [110 500 280 100 270 200]
 [130 420 320  85 240 170]
 [150 550 350 120 300 220]
 [100 400 260  75 220 160]]
[[ 95 380 240  65 190 140]
 [ 85 420 230  75 210 155]
 [105 350 270  60 180 130]
 [125 470 295  90 235 175]
 [ 75 330 205  55 165 120]]


Question 101: Closing Stock

Calculate closing stock using:

Closing Stock = Opening Stock - Units Sold

In [104]:
import numpy as np
closing_stock = opening_stock - units_sold
print("Closing Stock: ", closing_stock)

Closing Stock:  [[25 70 60 25 60 40]
 [25 80 50 25 60 45]
 [25 70 50 25 60 40]
 [25 80 55 30 65 45]
 [25 70 55 20 55 40]]


Question 102: Low-Stock Identification

Identify store-category combinations where closing stock is below 30 units.

In [105]:
import numpy as np
low_stock_indices = np.where(closing_stock < 30)
low_stock_stores = low_stock_indices[0]
low_stock_categories = low_stock_indices[1]
print("Low-Stock Stores: ", low_stock_stores)
print("Low-Stock Categories: ", low_stock_categories)

Low-Stock Stores:  [0 0 1 1 2 2 3 4 4]
Low-Stock Categories:  [0 3 0 3 0 3 0 0 3]


Question 103: Stock Availability Percentage

Calculate the percentage of opening stock that remains unsold.

In [106]:
import numpy as np
unsold_stock_percentage = np.mean(opening_stock == 0) * 100
print("Percentage of Unsold Stock: ", unsold_stock_percentage)

Percentage of Unsold Stock:  0.0


Question 104: Fast-Moving Products

A product is considered fast-moving when more than 80% of its opening stock has been sold.

Identify fast-moving store-category combinations.

In [107]:
import numpy as np
fast_moving_indices = np.where(np.sum(units_sold, axis=0) / np.sum(opening_stock, axis=0) > 0.8)
fast_moving_stores = fast_moving_indices[0]
fast_moving_categories = fast_moving_indices[0]
print("Fast-Moving Stores: ", fast_moving_stores)
print("Fast-Moving Categories: ", fast_moving_categories)

Fast-Moving Stores:  [1 2]
Fast-Moving Categories:  [1 2]


Question 105: Category-Wise Units Sold

Calculate the total units sold for each product category.

In [108]:
import numpy as np
total_units_sold = np.sum(units_sold, axis=0)
print("Total Units Sold: ", total_units_sold)

Total Units Sold:  [ 485 1950 1240  345  980  720]


Question 106: Store-Wise Units Sold

Calculate total units sold by each store.

In [109]:
import numpy as np
total_units_sold_by_store = np.sum(units_sold, axis=1)
print("Total Units Sold by Store: ", total_units_sold_by_store)

Total Units Sold by Store:  [1110 1175 1095 1390  950]


Question 107: Best Store by Unit Sales

Identify the store that sold the highest total number of units.

In [110]:
import numpy as np
best_store_index = np.argmax(total_units_sold_by_store)
print("Best Store by Unit Sales: ", best_store_index)

Best Store by Unit Sales:  3


Question 108: Reorder Requirement

A store should reorder a category when closing stock is below 25 units.

Create a Boolean reorder matrix.

In [111]:
import numpy as np
reorder_required = closing_stock < 25
print("Boolean Reorder Required Matrix: ", reorder_required)

Boolean Reorder Required Matrix:  [[False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False False False False]
 [False False False  True False False]]


Question 109: Reorder Quantity

Assume each category must maintain 100 units after reordering.

Calculate reorder quantities only for combinations where closing stock is below 25.

For all other combinations, return zero.

In [112]:
import numpy as np
reorder_quantity = np.where(closing_stock < 25, 100 - closing_stock, 0)
print("Reorder Quantity: ", reorder_quantity)

Reorder Quantity:  [[ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0 80  0  0]]


Part 19: Advanced NumPy Questions

Question 110: Cumulative Store Sales

Calculate cumulative category sales for each store using np.cumsum().

In [113]:
import numpy as np
cumulative_category_sales = np.cumsum(sales_data, axis=1)
print("Cumulative Category Sales: ", cumulative_category_sales)

Cumulative Category Sales:  [[ 850000. 1270000. 1270000. 1545000. 1735000. 1960000.]
 [ 780000. 1240000. 1535000. 1535000. 1745000. 1985000.]
 [ 920000. 1310000. 1650000. 1910000. 2095000. 2310000.]
 [1050000. 1050000. 1425000. 1770000. 2020000. 2310000.]
 [ 690000. 1095000. 1375000. 1600000. 1600000. 1805000.]]


Question 111: Cumulative Company Sales

Flatten the sales array and calculate cumulative company sales.

In [114]:
import numpy as np
flattened_sales = sales_data.flatten()
cumulative_company_sales = np.cumsum(flattened_sales)
print("Cumulative Company Sales: ", cumulative_company_sales)

Cumulative Company Sales:  [  850000.  1270000.  1270000.  1545000.  1735000.  1960000.  2740000.
  3200000.  3495000.  3495000.  3705000.  3945000.  4865000.  5255000.
  5595000.  5855000.  6040000.  6255000.  7305000.  7305000.  7680000.
  8025000.  8275000.  8565000.  9255000.  9660000.  9940000. 10165000.
 10165000. 10370000.]


Question 112: Sales Difference Between Categories

Calculate the difference between consecutive category sales for each store using np.diff().

In [115]:
import numpy as np
sales_difference_between_categories = np.diff(sales_data, axis=1)
print("Sales Difference Between Categories: ", sales_difference_between_categories)

Sales Difference Between Categories:  [[ -430000.  -420000.   275000.   -85000.    35000.]
 [ -320000.  -165000.  -295000.   210000.    30000.]
 [ -530000.   -50000.   -80000.   -75000.    30000.]
 [-1050000.   375000.   -30000.   -95000.    40000.]
 [ -285000.  -125000.   -55000.  -225000.   205000.]]


Question 113: Unique Sales Values

Find all unique sales values in sales_data.

Also count the frequency of each value.

In [116]:
import numpy as np
unique_sales_values, value_counts = np.unique(sales_data, return_counts=True)
print("Unique Sales Values: ", unique_sales_values)
print("Value Counts: ", value_counts)

Unique Sales Values:  [      0.  185000.  190000.  205000.  210000.  215000.  225000.  240000.
  250000.  260000.  275000.  280000.  290000.  295000.  340000.  345000.
  375000.  390000.  405000.  420000.  460000.  690000.  780000.  850000.
  920000. 1050000.]
Value Counts:  [4 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Question 114: Search for Specific Sales

Check whether the value ₹4,20,000 exists in the sales array.

Return its location.

In [117]:
import numpy as np
value_to_search = 420000
location_of_value = np.where(sales_data == value_to_search)
print("Location of Value: ", location_of_value)

Location of Value:  (array([0]), array([1]))


Question 115: Compare Sales and Cost

Create a Boolean array showing whether sales are greater than cost for every combination.

Verify whether all combinations are profitable using np.all().

In [118]:
import numpy as np
sales_greater_than_cost = sales_data > cost_data
all_combinations_profitable = np.all(sales_greater_than_cost)
print("Sales Greater Than Cost: ", sales_greater_than_cost)
print("All Combinations Profitable: ", all_combinations_profitable)

Sales Greater Than Cost:  [[ True  True False  True  True  True]
 [ True  True  True False  True  True]
 [ True  True  True  True  True  True]
 [ True False  True  True  True  True]
 [ True  True  True  True False  True]]
All Combinations Profitable:  False


Question 116: Clip Profit Values

**For reporting purposes, management wants profit values limited to:

Minimum: ₹75,000 Maximum: ₹2,50,000 Use np.clip() to create a reporting profit array.**

In [119]:
import numpy as np
minimum_profit = 75000
maximum_profit = 250000
reporting_profit = np.clip(profit, minimum_profit, maximum_profit)
print("Reporting Profit: ", reporting_profit)

Reporting Profit:  [250000. 250000. 250000. 245000. 250000.]


Question 117: Normalize Sales Data

Normalize all sales values using min-max normalization:

In [120]:
import numpy as np
min_sales = np.min(sales_data)
max_sales = np.max(sales_data)
normalized_sales = (sales_data - min_sales) / (max_sales - min_sales)
print("Normalized Sales: ", normalized_sales)

Normalized Sales:  [[0.80952381 0.4        0.         0.26190476 0.18095238 0.21428571]
 [0.74285714 0.43809524 0.28095238 0.         0.2        0.22857143]
 [0.87619048 0.37142857 0.32380952 0.24761905 0.17619048 0.2047619 ]
 [1.         0.         0.35714286 0.32857143 0.23809524 0.27619048]
 [0.65714286 0.38571429 0.26666667 0.21428571 0.         0.1952381 ]]


Question 118: Standardize Sales Data

Standardize sales using:

Standardized Sales = (Sales - Mean Sales) / Standard Deviation

In [122]:
import numpy as np
mean_sales = np.mean(sales_data)
std_sales = np.std(sales_data)
standardized_sales = (sales_data - mean_sales) / std_sales
print("Standardized Sales: ", standardized_sales)

Standardized Sales:  [[ 1.92113083e+00  2.83154115e-01 -1.31673012e+00 -2.69186871e-01
  -5.92972967e-01 -4.59649280e-01]
 [ 1.65448346e+00  4.35524042e-01 -1.93001908e-01 -1.31673012e+00
  -5.16788003e-01 -4.02510558e-01]
 [ 2.18777820e+00  1.68876669e-01 -2.15857397e-02 -3.26325594e-01
  -6.12019207e-01 -4.97741762e-01]
 [ 2.68298047e+00 -1.31673012e+00  1.11737947e-01 -2.53949879e-03
  -3.64418076e-01 -2.12048149e-01]
 [ 1.31165112e+00  2.26015392e-01 -2.50140630e-01 -4.59649280e-01
  -1.31673012e+00 -5.35834244e-01]]


Question 119: Round Values

Convert profit margin values into:

Two decimal places Nearest whole number Floor values Ceiling values

In [123]:
import numpy as np
profit_margin = profit / total_sales
rounded_profit_margin = np.round(profit_margin, 2)
nearest_whole_number_profit_margin = np.round(profit_margin)
floor_values_profit_margin = np.floor(profit_margin)
ceiling_values_profit_margin = np.ceil(profit_margin)
print("Rounded Profit Margin: ", rounded_profit_margin)
print("Nearest Whole Number Profit Margin: ", nearest_whole_number_profit_margin)
print("Floor Values Profit Margin: ", floor_values_profit_margin)
print("Ceiling Values Profit Margin: ", ceiling_values_profit_margin)

Rounded Profit Margin:  [0.15 0.15 0.26 0.11 0.18]
Nearest Whole Number Profit Margin:  [0. 0. 0. 0. 0.]
Floor Values Profit Margin:  [0. 0. 0. 0. 0.]
Ceiling Values Profit Margin:  [1. 1. 1. 1. 1.]


Question 120: Save and Load Data

Save the following arrays as NumPy binary files:

sales_data.npy cost_data.npy profit_data.npy Load them back and verify that the loaded arrays are equal to the original arrays.

In [124]:
import numpy as np
np.save("sales_data.npy", sales_data)
np.save("cost_data.npy", cost_data)
np.save("profit_data.npy", profit)
loaded_sales_data = np.load("sales_data.npy")
loaded_cost_data = np.load("cost_data.npy")
loaded_profit_data = np.load("profit_data.npy")
print("Loaded Sales Data: ", loaded_sales_data)
print("Loaded Cost Data: ", loaded_cost_data)
print("Loaded Profit Data: ", loaded_profit_data)

Loaded Sales Data:  [[ 850000.  420000.       0.  275000.  190000.  225000.]
 [ 780000.  460000.  295000.       0.  210000.  240000.]
 [ 920000.  390000.  340000.  260000.  185000.  215000.]
 [1050000.       0.  375000.  345000.  250000.  290000.]
 [ 690000.  405000.  280000.  225000.       0.  205000.]]
Loaded Cost Data:  [[640000 315000 220000 205000 125000 160000]
 [590000 350000 210000 225000 140000 170000]
 [700000 295000 245000 195000 120000 155000]
 [790000 390000 265000 250000 165000 205000]
 [530000 310000 205000 170000 115000 145000]]
Loaded Profit Data:  [295000. 300000. 600000. 245000. 330000.]


Part 20: Final Retail Analytics Project

Prepare a complete NumPy-based retail performance report.

Your report must contain the following information:

Company Summary Total company sales Total company cost Total company profit Overall company profit margin Average transaction value Highest individual sales value Lowest individual sales value Store Summary For every store, display:

Total sales Total cost Total profit Profit margin Number of category targets achieved Total units sold Expansion eligibility Category Summary For every category, display:

Total sales Total cost Total profit Profit margin Average sales Number of stores achieving the target Total units sold Management Recommendations Based on the analysis, identify:

Best-performing store Lowest-performing store Most profitable category Lowest-profit category Store recommended for expansion Category requiring additional marketing Store-category combinations needing cost optimization Store-category combinations requiring inventory reorder Expected Final Output Format SMARTMART RETAIL PERFORMANCE REPORT
COMPANY SUMMARY
Total Sales: Total Cost: Total Profit: Overall Profit Margin:

BEST-PERFORMING STORE
Store: Sales: Cost: Profit: Profit Margin:

MOST PROFITABLE CATEGORY
Category: Sales: Cost: Profit: Profit Margin:

EXPANSION RECOMMENDATIONS
Eligible Stores:

COST OPTIMIZATION
Store: Category: Cost: Profit Margin:

INVENTORY REORDER
Store: Category: Closing Stock: Reorder Quantity:

In [125]:
import numpy as np
stores = np.array([
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Mumbai",
    "Pune"
])
categories = np.array([
    "Electronics",
    "Groceries",
    "Clothing",
    "Furniture",
    "Beauty",
    "Sports"
])
sales_data = np.array([
    [850000, 420000, 310000, 275000, 190000, 225000],
    [780000, 460000, 295000, 310000, 210000, 240000],
    [920000, 390000, 340000, 260000, 185000, 215000],
    [1050000, 510000, 375000, 345000, 250000, 290000],
    [690000, 405000, 280000, 225000, 175000, 205000]
])
cost_data = np.array([
    [640000, 315000, 220000, 205000, 125000, 160000],
    [590000, 350000, 210000, 225000, 140000, 170000],
    [700000, 295000, 245000, 195000, 120000, 155000],
    [790000, 390000, 265000, 250000, 165000, 205000],
    [530000, 310000, 205000, 170000, 115000, 145000]
])
total_sales = np.sum(sales_data, axis=1)
total_cost = np.sum(cost_data, axis=1)
profit = total_sales - total_cost
overall_profit_margin = np.mean(profit / total_sales)
average_transaction_value = np.mean(total_sales)
highest_individual_sales_value = np.max(total_sales)
lowest_individual_sales_value = np.min(total_sales)
total_sales_by_store = np.sum(sales_data, axis=0)
total_cost_by_store = np.sum(cost_data, axis=0)
total_profit_by_store = total_sales_by_store - total_cost_by_store
profit_margin_by_store = total_profit_by_store / total_sales_by_store
number_of_category_targets_achieved = np.sum(sales_data >= 400000, axis=0)
total_units_sold_by_store = np.sum(sales_data, axis=1)
expansion_eligibility_by_store = total_units_sold_by_store >= 5
total_sales_by_category = np.sum(sales_data, axis=1)
total_cost_by_category = np.sum(cost_data, axis=1)
total_profit_by_category = total_sales_by_category - total_cost_by_category
profit_margin_by_category = total_profit_by_category / total_sales_by_category
average_sales_by_category = np.mean(sales_data, axis=0)
number_of_stores_achieving_target = np.sum(sales_data >= 400000, axis=1)
total_units_sold_by_category = np.sum(sales_data, axis=0)
best_performing_store_index = np.argmax(total_sales_by_store)
lowest_performing_store_index = np.argmin(total_sales_by_store)
most_profitable_category_index = np.argmax(total_profit_by_category)
lowest_profitable_category_index = np.argmin(total_profit_by_category)
store_recommended_for_expansion_index = np.argmax(expansion_eligibility_by_store)
category_requiring_additional_marketing_index = np.argmax(number_of_stores_achieving_target)
store_category_combinations_requiring_cost_optimization_indices = np.where(sales_data < 400000)
store_category_combinations_requiring_inventory_reorder_indices = np.where(sales_data < 300000)
print("Company Summary")
print("Total sales: ", total_sales)
print("Total cost: ", total_cost)
print("Total profit: ", profit)
print("Overall profit margin: ", overall_profit_margin)
print("Average transaction value: ", average_transaction_value)
print("Highest individual sales value: ", highest_individual_sales_value)
print("Lowest individual sales value: ", lowest_individual_sales_value)
print("Store Summary")
print("Total sales of Store: ", total_sales_by_store)
print("Total cost of Store: ", total_cost_by_store)
print("Total profit of Store: ", total_profit_by_store)
print("Profit margin of Store: ", profit_margin_by_store)
print("Number of category targets achieved: ", number_of_category_targets_achieved)
print("Total units sold by Store: ", total_units_sold_by_store)
print("Expansion eligibility of Store: ", expansion_eligibility_by_store)
print("Category saummary")
print("Total sales of Category: ", total_sales_by_category)
print("Total cost of Category: ", total_cost_by_category)
print("Total profit of Category: ", total_profit_by_category)
print("Profit margin of Category: ", profit_margin_by_category)
print("Average sales of Category: ", average_sales_by_category)
print("Number of stores achieving target: ", number_of_stores_achieving_target)
print("Total units sold by Category: ", total_units_sold_by_category)
print("Management Recommendations")
print("Best performing store: ", stores[best_performing_store_index])
print("Lowest performing store: ", stores[lowest_performing_store_index])
print("Most profitable category: ", categories[most_profitable_category_index])
print("Lowest profitable category: ", categories[lowest_profitable_category_index])
print("Store recommended for expansion: ", stores[store_recommended_for_expansion_index])
print("Category requiring additional marketing: ", categories[category_requiring_additional_marketing_index])
print("Store-category combinations requiring cost optimization: ", store_category_combinations_requiring_cost_optimization_indices)
print("Store-category combinations requiring inventory reorder: ", store_category_combinations_requiring_inventory_reorder_indices)
print("SMARTMART RETAIL PERFORMANCE REPORT")
print("==================================")
print("COMPANY SUMMARY")
print("---------------")
print("Total Sales          : ", total_sales)
print("Total Cost           : ", total_cost)
print("Total Profit         : ", profit)
print("Overall Profit Margin: ", overall_profit_margin)
print()
print("BEST-PERFORMING STORE")
print("--------------------")
print("Store        : ", stores[best_performing_store_index])
print("Sales        : ", total_sales_by_store[best_performing_store_index])
print("Cost         : ", total_cost_by_store[best_performing_store_index])
print("Profit       : ", total_profit_by_store[best_performing_store_index])
print("Profit Margin: ", profit_margin_by_store[best_performing_store_index])
print()
print("MOST PROFITABLE CATEGORY")
print("-----------------------")
print("Category     : ", categories[most_profitable_category_index])
print("Sales        : ", total_sales_by_category[most_profitable_category_index])
print("Cost         : ", total_cost_by_category[most_profitable_category_index])
print("Profit       : ", total_profit_by_category[most_profitable_category_index])
print("Profit Margin: ", profit_margin_by_category[most_profitable_category_index])
print("EXPANSION RECOMMENDATIONS")
print("------------------------")
print("Eligible Stores: ", stores[expansion_eligibility_by_store])
print()
print("COST OPTIMIZATION")
print("----------------")
print("Store        : ", stores[store_category_combinations_requiring_cost_optimization_indices[0]])
print("Category     : ", categories[store_category_combinations_requiring_cost_optimization_indices[1]])
print("Cost         : ", cost_data[store_category_combinations_requiring_cost_optimization_indices[0], store_category_combinations_requiring_cost_optimization_indices[1]])
print("Profit Margin: ", profit_margin_by_category[store_category_combinations_requiring_cost_optimization_indices[0]])
print()
print("INVENTORY REORDER")
print("----------------")
print("Store           : ", stores[store_category_combinations_requiring_inventory_reorder_indices[0]])
print("Category        : ", categories[store_category_combinations_requiring_inventory_reorder_indices[1]])
print("Closing Stock   : ", sales_data[store_category_combinations_requiring_inventory_reorder_indices[0], store_category_combinations_requiring_inventory_reorder_indices[1]])
print("Reorder Quantity: ", 100 - sales_data[store_category_combinations_requiring_inventory_reorder_indices[0], store_category_combinations_requiring_inventory_reorder_indices[1]])

Company Summary
Total sales:  [2270000 2295000 2310000 2820000 1980000]
Total cost:  [1665000 1685000 1710000 2065000 1475000]
Total profit:  [605000 610000 600000 755000 505000]
Overall profit margin:  0.26296725840097784
Average transaction value:  2335000.0
Highest individual sales value:  2820000
Lowest individual sales value:  1980000
Store Summary
Total sales of Store:  [4290000 2185000 1600000 1415000 1010000 1175000]
Total cost of Store:  [3250000 1660000 1145000 1045000  665000  835000]
Total profit of Store:  [1040000  525000  455000  370000  345000  340000]
Profit margin of Store:  [0.24242424 0.2402746  0.284375   0.2614841  0.34158416 0.2893617 ]
Number of category targets achieved:  [5 4 0 0 0 0]
Total units sold by Store:  [2270000 2295000 2310000 2820000 1980000]
Expansion eligibility of Store:  [ True  True  True  True  True]
Category saummary
Total sales of Category:  [2270000 2295000 2310000 2820000 1980000]
Total cost of Category:  [1665000 1685000 1710000 2065000 1